name: OCTIS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python == 3.9
  - wordcloud
  - transformers
  - spacy
  - pip
  - pip:
      - scikit-learn ==1.1.0
      - octis
      - torch


