name: OCTIS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python == 3.9
  - notebook
  - transformers
  - spacy
  - dask
  - pip
  - pip:
      - scikit-learn ==1.1.0
      - octis
      - torch
      - wordcloud